### ISSUE TITLE
Error when build 

### ISSUE THREAD

**Issue by ahmaddarwesh** [Vanethos/flutter_connectivity_widget#22]
This issue faced me when I trying to build Android.
And on iOS simulator when build debug showing white screen.

```
Note: Recompile with -Xlint:deprecation for details.                    
/Users/ahmaddarwesh/Desktop/delivery_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:18: error: constructor ConnectivityPlugin in class ConnectivityPlugin cannot be applied to given types;
    flutterEngine.getPlugins().add(new io.flutter.plugins.connectivity.ConnectivityPlugin());
                                   ^                                    
  required: Registrar                                                   
  found: no arguments                                                   
  reason: actual and formal argument lists differ in length             
1 error                                                                 
                                                                        
FAILURE: Build failed with an exception.      
```                          
                         
But when I remove connectivity_widget package everything run and build successfully.

### some info:

**Flutter version 1.22.5**
 **Channel stable**
**Dart version 2.10.4**

### pubspace.yaml file

```
name: delivery_app
description: description
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
  
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  outline_material_icons: ^0.1.1
  get: ^3.24.0
  graphql_flutter: ^3.1.0
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  expandable: ^4.1.4
  flutter_bounce: ^1.0.8
  flutter_screenutil: ^4.0.2+5
  google_fonts: ^1.1.1
  auto_size_text: ^2.1.0
  sliding_sheet: ^0.4.1
  url_launcher: ^5.7.10
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.27
  timeago: ^2.0.29
  ffloat: ^1.0.1
  connectivity_widget: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.13


flutter:

  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true

```
